### ISSUE TITLE
Conflicting Types for cntl_de_thresholds_Tbl 

### ISSUE THREAD

**Issue by JimKaidyNASA** [nasa/SIL#13]
The following errors are occurring when attempting to build tables (cfs_build_app_tbls).
![image](https://user-images.githubusercontent.com/52501916/64965158-799d5d80-d86a-11e9-90ce-b8a59c18d9a6.png)

**Comment by SpaceSteve121** [comment]
Can you post the source file containing the table definition?

Your generated code appears to have a different structure than the example code found [here](https://github.com/nasa/SIL/blob/master/tests/eci_compatibility/generatedCode.zip).

For that example code, the extern declaration `extern Tbl_b *Tbl ;` is in the private header (`SILTest_private.h`), whereas yours appears to be in your model header (`Controller.h`). In the example code, the private header is not in the include hierarchy for `Tbl.h`, which means there's no conflicting declarations. That's not the case for yours, potentially due to your model configuration, though its hard to say exactly what's causing that. 

Can you try to compare your generated code to the example I linked above and try to note any differences in the structure of the code?

**Comment by JimKaidyNASA** [comment]
46 lines long.  I will look at the example.

![image](https://user-images.githubusercontent.com/52501916/64968027-7b1d5480-d86f-11e9-9628-d8915f643305.png)

**Comment by SpaceSteve121** [comment]
The issue appears to be the include for `Controller.h` in this file... that's not present in the example, which instead included `SILTest_types.h` (which includes `Tbl.h`, which has the typedef).

Did you resolve the issues with the compact formatting? Otherwise, I'm not sure what might be causing this difference in your generated code.

**Comment by JimKaidyNASA** [comment]
I was just looking into that.  I thought we had resolved it.  I know I generated a new autocode with the option set properly.  I will look further.

**Comment by JimKaidyNASA** [comment]
The Controller version from my last update of the autocode to have it produce the private include, etc, does not have an fsw directory.  It seems to have been added in after the autocode production.  Does this make any sense?  I will be checking with Tawanda on this.

**Comment by SpaceSteve121** [comment]
I'm not sure I follow the order of operations here... are you saying you fixed the generation of a `<model>_private.h` in a previous build and that this is a regression?

Generally the code is produced in a folder called `<model_name>_<coder_target>_rtw`, which for the example is `SILTest_cfs_ert_rtw`. This then has to be massaged into a directory structure consistent with your project's organization. Generally a CFS app has a `fsw` directory (which contains the source code) and a `tbl` directory (which you'd need to populate with your table-related source files), among others. I don't actually know what the requirements of the build system are, but I've seen those commonly. You need to implement the organizational structure consistent with your project... the SIL does not do that for you.

**Comment by JimKaidyNASA** [comment]
It is not intentionally a regression but it looks like you could call it that.  I have the the latest one, which does not contain the fsw directory but has all the new ones when we set the autocode options correctly.  So the massaging into the directory structure is something I didn't know about.  But you can see below the new directory compared the old one which has the fsw in it.  I will look into how that fsw is created.

  
![image](https://user-images.githubusercontent.com/52501916/64972164-d0109900-d876-11e9-9986-1dc5cf0c2b4d.png)

**Comment by SpaceSteve121** [comment]
Note that you can see an example of building a CFS app directory in [testWithECI.sh](https://github.com/nasa/SIL/blob/master/tests/eci_compatibility/testWithECI.sh), which might give you an idea of what directories are used in that example, but I can't comment of which of those are convention and which are required.

**Comment by SpaceSteve121** [comment]
@JimKaidyNASA Can you please post some information about how you resolved this for future reference?

**Comment by JimKaidyNASA** [comment]
Was planning on that.  The perfsid and msgid files had not be created under the mission_inc and platform_inc respectively.  The header for the eci_interface.h had to be updated as well.

I am going to open a new issue as we have gotten past this one now.

**Comment by SpaceSteve121** [comment]
@JimKaidyNASA Can you explain the updates needed to eci_interface.h to get it working? As I've said, the generated code is designed to work out-of-the box, so if that's not the case then we'd like to fix the SIL.

**Comment by JimKaidyNASA** [comment]
The last two are the ones I had to add (per Tawanda's direction).

![image](https://user-images.githubusercontent.com/52501916/65174835-a2b31f00-da1f-11e9-9546-91282f22805a.png)

**Comment by SpaceSteve121** [comment]
Those includes do not need to be added by hand. The SIL has the ability to generate those includes.

If you look at you model configuration, in the `CFS Target Settings` tab there's configuration fields labeled `Message ID Header` and `Performance ID Header` which allow you to specify the names of your perfID and msgID headers. Putting values into those fields will cause the SIL to generate those includes in `eci_interface.h`.

The image below shows the settings from `SIL\tests\eci_compatibility\model\SILTest.slx`:

![image](https://user-images.githubusercontent.com/45206558/65175401-d2165b80-da20-11e9-836e-0a4182ec655c.png)

which generates the header shown below:

![image](https://user-images.githubusercontent.com/45206558/65175666-4b15b300-da21-11e9-9ce2-f0f4e3aa6bc9.png)

If that functionality isn't sufficient for your use case, can you please suggest a change that would make it compatible?

**Comment by JimKaidyNASA** [comment]
As I understand the process and have documented for the Controller app, (named cnt), I have learned that I must manually create a number of features under the cfs/apps directory.  
1. Bring the cnt directory (with all the autocode) under apps
2. Create an fsw directory under cnt
3. Create subdirectories under cnt/fsw which include eci_in, for_build, mission_inc, platform_inc, src and tables 
4. Among a number of things that are done manually, i must create the perfids and msgids in the respective mission_inc and platform_inc directories.   These two include files must also be added back into the fsw/src/eci_interface.h which as you state is auto generated.  I would welcome SIL doing all of this since it should lend itself to automation.  My intent is to have a procedure (I have a draft of the document completed), that can be converted into a script with stream edit (sed) commands that do all this.  But to me, out of the box would be not having to do most of these edits which frankly are setting these things up to be cfs  compatible.
